Meteor.methods({
  insertFriend:function(friend){
    Friends.insert(friend);
  },
  insertTime:function(time){
    check(time,String);
    Times.insert(time);
  },
  insertPlace:function(place){
    check(place,String);
    Places.insert(place);
  },
  sayhilib: function(){
    console.log("hi!");
  },
  insertComment:function(comment){
    check(comment,String);
    Comments.insert(comment);
  },
  removeComment:function(commentId){
    Comments.remove(commentId);
  },
  removeAll:function(password){
    check(password,String);
    //check to see if password == "zz9911"
    if(password=="zz9911"){
      console.log("removed all friends requesting meal buddies");
      Friends.remove({});
    }
  },
  insertSetting:function(setting){
    Settings.insert(setting);
  },
  updateSetting:function(setting){
    Settings.update({_id:Settings.findOne({user:Meteor.userId()})._id},
     {
      $set:{greeting:setting.greeting},
    });
  },
  //removeSettings:function(){
    //Settings.remove({});
  //},
})
